### ISSUE TITLE
mvp-cockpit: Error during execution of the blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#263]
After adding a blueprint to create a new VDC and trying to execute it I get this:

Error during execution of the blueprint:\n ERROR: could not execute job:job: vdc!vdc4yves3

See repository yves03 in the Cockpit for Artilium: https://artilium.aydo2.com/ays81/ays81/Blueprints?ayspath=/optvar/cockpit_repos/yves03

**Comment by FastGeert** [comment]
I know, we looked at that one as well.

**Comment by yveskerwyn** [comment]
Here's the full stack trace:

```
[Mon28 08:57] - ...le/baselib/atyourservice81/Service.py:540  - INFO     - schedule action install on service:vdc!vdc4yves
[Mon28 08:57] - ...le/baselib/atyourservice81/Service.py:560  - INFO     - action install already in ok state, don't schedule again
/opt/jumpscale8/lib/JumpScale/data/capnp/ModelBase.py:67: UserWarning: This message has already been written once. Be very careful that you're not setting Text/Struct/List fields more than once, since that will cause memory leaks (both in memory and in the serialized data). You can disable this warning by setting the `_is_written` field of this object to False after every write.
  buff = self.dbobj.to_bytes()
[Mon28 08:57] - .../atyourservice81/AtYourServiceRepo.py:433  - INFO     - init service: service:vdc!vdc4yves
/opt/jumpscale8/lib/JumpScale/data/capnp/ModelBase.py:67: UserWarning: This message has already been written once. Be very careful that you're not setting Text/Struct/List fields more than once, since that will cause memory leaks (both in memory and in the serialized data). You can disable this warning by setting the `_is_written` field of this object to False after every write.
  buff = self.dbobj.to_bytes()
[Mon28 08:57] - .../atyourservice81/AtYourServiceRepo.py:433  - INFO     - init service: service:vdc!vdc4yves3
Error of job: vdc!vdc4yves3 (init):
*TRACEBACK*********************************************************************************
no producer g8client found. cannot continue init of service:vdc!vdc4yves3


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 490, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 137, in blueprint
    repo.blueprintExecute(role=role, instance=instance, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 326, in blueprintExecute
    self.init(role=role, instance=instance)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 434, in init
    service.init()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 521, in init
    job.executeInProcess()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 177, in executeInProcess
    raise j.exceptions.RuntimeError("could not execute job:%s" % self)
JSExceptions.RuntimeError: ERROR: could not execute job:job: vdc!vdc4yves3 (init) ((type:runtime.error)
```

**Comment by yveskerwyn** [comment]
OK, now I see what the problem is, let me fix it
