### ISSUE TITLE
mvp-cockpit: ays destroy didn't fylly clean up

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#300]
As a follow-up to [issue #299](https://github.com/Jumpscale/jscockpit/issues/299) I did an `ays destroy` and then again an `ays blueprint` => **JSExceptions.Input: ERROR: could not find parent:vdc4yves01 for service:autosnapshotting!snapshotting4yves01**

See: http://172.98.207.199:7182/ays81/repo?repo=yves01&repopath=/optvar/cockpit_repos/yves01

Trace back:

```
root@vm-61:/optvar/cockpit_repos/yves01# ays destroy
root@vm-61:/optvar/cockpit_repos/yves01# ays blueprint
[Mon05 11:43] - ...le/baselib/atyourservice81/Service.py:45   - INFO     - create service snapshotting4yves01 from autosnapshotting

**** TRACEBACK ***
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 538, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 137, in blueprint
    repo.blueprintExecute(role=role, instance=instance, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 343, in blueprintExecute
    bp.load(role=role, instance=instance)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Blueprint.py", line 179, in load
    actor.serviceCreate(instance=bpinstance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 386, in serviceCreate
    service = Service(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 23, in __init__
    self._initFromActor(actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 95, in _initFromActor
    parent = self._initParent(actor, args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 132, in _initParent
    (parent_name, self), level=1, source="", tags="", msgpub="")
JSExceptions.Input: ERROR: could not find parent:vdc4yves01 for service:autosnapshotting!snapshotting4yves01, found 0 ((type:input.error)
```

**Comment by rkhamis** [comment]
Turns out that the blueprints were executed in the wrong order. Will look into having AYS load all the blueprints in one go.
