### ISSUE TITLE
Trying to execute autoscale on machine once the blueprint is executed and before run

### ISSUE THREAD

**Issue by ramezsaeed** [Jumpscale/jscockpit#325]
- Got a lot of this error in tmux deamon logs, once a blueprint had been executed and include creating a VM 
- this happens before running the blueprint
- and once I run the bp and machine is created this error disapears

```
[Thu29 14:08] - ...ib/JumpScale/sal/nettools/NetTools.py:67   - DEBUG    - test tcp connection to '' on port 2200
[Thu29 14:08] - ...ib/JumpScale/clients/ssh/SSHClient.py:191  - ERROR    - Cannot connect to ssh server :2200 with login:root and using sshkey:/optvar/cockpit_repos/s3server4/services/sshkey!auto_0/id_rsa
Error of job: fs.btrfs!data (autoscale):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 169, in executeInProcess
    res = self.method(job=self)
  File "/tmp/actions/fs.btrfs/autoscale.py", line 9, in action
    code, out, err = cuisine.core.run('btrfs filesystem  usage -b {}'.format(service.model.data.mount), die=False)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1033, in run
    if "cygwin" in self.uname:
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1251, in uname
    self._uname = self._executor.execute("uname -a", showout=False)[1].lower()
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 251, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 179, in transport
    "Could not connect to %s:%s" % (self.addr, self.port))
JSExceptions.RuntimeError: ERROR: Could not connect to :2200 ((type:runtime.error)


******************************************************************************************
```

Blueprint

```
g8client__main:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 's3user'
    password: '********'
    account: 's3_acc'

vdc__scality22:
    g8client: 'main'
    location: 'du-conv-2'

disk.ovc__disk1:
  size: 1000

s3__s3vm:
    vdc: 'scality22'
    disk:
      - 'disk1'
    hostprefix: 's3app22'
```

**Comment by rkhamis** [comment]
The log shows that the machine didn't get an IP. Please update after checking the env?

**Comment by ramezsaeed** [comment]
the vm is not even created yet,
the bp only executed and didn't run yet
so nothing in the env created

**Comment by rkhamis** [comment]
Indeed a bug. Daemon shouldn't pick up `autoscale` until `install` has been executed

**Comment by rkhamis** [comment]
Issue created on code repo. https://github.com/Jumpscale/jumpscale_core8/issues/692
