### ISSUE TITLE
[AYS API] Failure with get template API

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jscockpit#384]
Calling the get template API with url [/ays/repository/<repository>/template] fails with the following error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/github/jumpscale/jscockpit/ays_api/ays.py", line 472, in getTemplate
    template = template_view(tmpl)
  File "/opt/code/github/jumpscale/jscockpit/ays_api/views.py", line 91, in template_view
    actions_file = j.sal.fs.fileGetContents()
TypeError: fileGetContents() missing 1 required positional argument: 'filename'

-->

```

the code is actually doing this...for real!!

```
def template_view(template):
    actions_path = j.sal.fs.joinPaths(template.path, 'actions.py')
    actions_file = None
    if j.sal.fs.exists(actions_path):
        actions_file = j.sal.fs.fileGetContents()
```

**Comment by rkhamis** [comment]
Nice test suite :D

**Comment by xmonader** [comment]
Fixed in https://github.com/Jumpscale/jscockpit/commit/cf1dba892452dbc9f9bdeef107207d0a3b438011
