### ISSUE TITLE
[AYS API] Failure while using update template API

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jscockpit#385]
Using the update template API fails with the following error
```
<!--

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/github/jumpscale/jscockpit/ays_api/ays.py", line 486, in updateTemplate
    return jsonify(error=e.message), 500
AttributeError: 'AttributeError' object has no attribute 'message'

-->

the e.message is used in other APIs as well

```

**Comment by xmonader** [comment]
`message` attribute got removed from BaseException (moved to use args[0] instead) and template variable was overriden as well.
Fixed in https://github.com/Jumpscale/jscockpit/commit/407f6ebf7abc2844b2f540e79d39d8815b89a9a3
