### ISSUE TITLE
Moehaha cockpit portal fails to load dockers gauge

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/jscockpit#54]
The cockpit portal shows the following error, but actually it should not show a dockers gauge at all.

![image](https://cloud.githubusercontent.com/assets/15246294/16376538/004539ec-3c61-11e6-93b8-3da67863f9b8.png)

Stacktrace shown:
```
**ERROR**: Could not execute macro vmgauge on home, error in macro. Error was:

Traceback (most recent call last):

File "/usr/local/lib/python3.5/dist-packages/JumpScale/portal/portal/MacroExecutor.py", line 312, in executeMacroOnContent

paramsExtra=paramsExtra, cmdstr=cmdstr, requestContext=ctx, content=content, page=page)

File "/opt/jumpscale8//lib/JumpScale/tools/taskletengine/TaskletEngine.py", line 115, in executeV2

return self.taskletEngines[groupname].executeV2(**args)

File "/opt/jumpscale8//lib/JumpScale/tools/taskletengine/TaskletEngine.py", line 254, in executeV2

params = tasklet.checkExecuteV2(args, params, tags)

File "/opt/jumpscale8//lib/JumpScale/tools/taskletengine/TaskletEngine.py", line 57, in checkExecuteV2

params = self.module.main(j, args, params, tags, self)

File "/optvar/cfg/portals/main/base/Cockpit/.macros/wiki/vmgauge/1_vmgauge.py", line 9, in main

[running.append(len(dockerhosts)) for dockerhosts in j.apps.system.atyourservice.listServices(role='dockerhost', ctx=args.requestContext).values()]

File "/optvar/cfg/portals/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py", line 61, in listServices

repos = self.listRepos()

File "/optvar/cfg/portals/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py", line 48, in listRepos

cl = self.get_client(**kwargs)

File "/optvar/cfg/portals/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py", line 32, in get_client

ctx = kwargs['ctx']

KeyError: 'ctx'
```

**Comment by zaibon** [comment]
![2016-07-06_1135x532_scrot](https://cloud.githubusercontent.com/assets/303164/16612993/1f2bae9e-436a-11e6-8d68-acd91d696d82.png)

Loading fine now
