### ISSUE TITLE
can't install cockpit via the deployer chatbot

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#83]
**Description**
Using the chatbot to install the cockpit in the be-scale-1 is producing the following status:

```
node!cockpit:init:OK
dns-client!main1:init:OK
dns-client!main1:install:OK
dns-client!main3:init:OK
dns-client!main3:install:OK
os!watticonsume:init:OK
cockpit!watticonsume:init:OK
sshkey!dns:init:OK
sshkey!dns:start:OK
sshkey!dns:install:OK
node!cockpitvm:init:OK
node!cockpitvm:install:INIT
sshkey!main:init:OK
sshkey!main:start:OK
sshkey!main:install:OK
vdcfarm!main:init:OK
vdcfarm!main:install:OK
dns-client!main2:init:OK
dns-client!main2:install:OK
vdc!watticonsume:init:OK
vdc!watticonsume:install:OK
os!pilot:init:OK
app-docker!watticonsume:init:OK
blueprint!pilot:init:OK
blueprint!pilot:install:OK
g8client!main:init:OK
g8client!main:install:OK
```

Which is look like good  and here is the cock pit vm:

![screenshot from 2016-07-11 15-46-25](https://cloud.githubusercontent.com/assets/17981089/16732670/0595773c-4787-11e6-8058-c403350cc44a.png)
![screenshot from 2016-07-11 15-46-16](https://cloud.githubusercontent.com/assets/17981089/16732675/08e7052c-4787-11e6-864e-67dce70c9bca.png)

But When I tried to access the portal I didn't find any thing
![screenshot from 2016-07-11 15-47-43](https://cloud.githubusercontent.com/assets/17981089/16732720/33c013a6-4787-11e6-85cb-4d9e78937aab.png)

**Software**
JumpScale

```
Core: 7.1.0b10
Portal: 7.1.0b10
```

OpenvCloud

```
Core: 2.1.0b10
```

OpenvStorage:

```
openvstorage-backend-core: 1.6.1-eugene-updates.4-1
alba: 0.8.1
openvstorage-webapps: 2.6.1-eugene-updates.18-1
openvstorage-backend-webapps: 1.6.1-eugene-updates.4-1
openvstorage-core: 2.6.1-eugene-updates.18-1
openvstorage-hc: 1.6.1-eugene-updates.4-1
openvstorage-cinder-plugin: 1.1.1-eugene-updates.1-1
openvstorage: 2.6.1-eugene-updates.18-1
openvstorage-backend: 1.6.1-eugene-updates.4-1
openvstorage-sdm: 1.5.1-eugene-updates.1-1
```

**Comment by zaibon** [comment]
the installation didn't went to the end, the bot would tell you the cockpit is installed and shows you some information about it. Like the IP, domain how to accesss and the ssh key used

**Comment by islamTaha12** [comment]
@zaibon so that is meaning that the bot stopped in a certain point  while the installation and it didn't produce any error so How I can work around that?

**Comment by zaibon** [comment]
>  that is meaning that the bot stopped in a certain point while the installation and it didn't produce any error

It's indeed probably the case. Someone needs to investigate the error that happened on the deployer chatbot and see what when wrong.

Here is the output of the bot.

```
*ERROR***********************************************************************************
action: run                  runid:85.255.197.106:2200:cloudscalers      (ERROR)
    CuisineCore.run.abf07e18be8ff2bae48cc862ee5a7dd8
    path: /opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py
ERROR:
    113
    No route to host
[Mon11 13:18] - ...lib/JumpScale/tools/actions/Action.py:775  - ERROR    - 
*SOURCECODE******************************************************************************

from __future__ import with_statement

import re

from JumpScale import j

import copy

from ActionDecorator import ActionDecorator

import base64, hashlib, os, re, string, tempfile, subprocess, types, threading, sys

import tempfile, functools

import platform

from JumpScale import j
args="""
[
 "test -d \/etc && echo **OK** ; true"
]
"""
kwargs="""
{
 "check_is_ok":true,
 "showout":false
}
"""

def run(self,cmd,die=True,debug=None,checkok=False,showout=True,profile=False,replaceArgs=True,check_is_ok=False):
    """
    @param profile, execute the bash profile first
    """
    # print (cmd)
    env = {}
    import copy
    if replaceArgs:
        cmd=self.args_replace(cmd)
    self.executor.curpath=self.cd
    # print ("CMD:'%s'"%cmd)
    if debug!=None:
        debugremember=copy.copy(debug)                                                                                                                                                                     [52/1410]
        self.executor.debug=debug

    if profile:
        ppath=self.cuisine.bash.profilePath
        if ppath:
            cmd=". %s && %s"%(ppath,cmd)
        if showout:
            self.logger.info("PROFILECMD:%s"%cmd)
        else:
            self.logger.debug("PROFILECMD:%s"%cmd)

    if '"' in cmd:
        cmd = cmd.replace('"', '\\"')
    if self.sudomode:
        passwd = self.executor.passwd if hasattr(self.executor, "passwd") else ''
        cmd = 'echo %s | sudo -SE bash -c "%s"' % (passwd, cmd)
    else:
        cmd = 'bash -c "%s"' % cmd

    path = self.executor.execute("echo $PATH", showout=False)[1]
    if "/usr/local/bin" not in path: 
        env = {"PATH": "%s:/usr/local/bin" % path}
    rc,out=self.executor.execute(cmd,checkok=checkok, die=False, combinestdr=False,showout=showout, env=env)

    out = self._clean(out)

    if rc>0:
        items2check=["sudo","wget","curl","git","openssl"]
        next=True
        while next==True:
            next=False
            if out.find("target not found: python3")!=-1 and not "python" in self.done:
                self.done.append("python")
                if self.isArch:
                    self.cuisine.package.install("python3")
                else:
                    self.cuisine.package.install("python3.5")
                next=True

            if out.find("pip3: command not found")!=-1 and not "pip" in self.done:

                self.done.append("pip")
                self.cuisine.installerdevelop.pip()
                next=True

            if out.lower().find("fatal error")!=-1 and out.lower().find("python.h")!=-1 \
                        and out.lower().find("no such")!=-1\
                        and not "pythondevel" in self.done:

                j.application.break_into_jshell("DEBUG NOW pythondevel not found")

                self.done.append("pythondevel")                                                                                                                                                             [0/1410]
                self.cuisine.installer.pythonDevelop()
                next=True

            for package in items2check:
                if out.find("not found")!=-1 and  out.find(package)!=-1:
                    if not package in self.done:
                        self.done.append(package)
                        self.cuisine.installer.base()
                        next=True

            if next:
                rc,out=self.executor.execute(cmd,checkok=checkok, die=False, combinestdr=False,showout=showout, env=env)

    if debug!=None:
        self.executor.debug=debugremember
    if rc>0 and die:
        raise j.exceptions.RuntimeError("could not execute %s,OUT:\n%s**NOSTACK**"%(cmd,out))
    out=out.strip()
    # print("output run: %s" % out)

    if check_is_ok:
        return out.find("**OK**")!=-1
    if die==False:
        return rc,out
    else:
        return out
[Mon11 13:18] - ...lib/JumpScale/tools/actions/Action.py:788  - ERROR    - 
*TRACEBACK*********************************************************************************

Traceback (most recent call last):
  File "/tmp/actions/85.255.197.106:2200:cloudscalers/run.py", line 63, in run
    path = self.executor.execute("echo $PATH", showout=False)[1]
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 105, in execute
    retcode,out=self.sshclient.execute(cmds2,die=die,showout=showout, combinestdr=combinestdr)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 204, in execute
    ch = self.transport.open_session()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 703, in open_session
    timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 824, in open_channel
    raise e
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 1739, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 387, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 250, in read_all
    x = self.__socket.recv(n)
OSError: [Errno 113] No route to host
[Mon11 13:18] - ...lib/JumpScale/tools/actions/Action.py:794  - ERROR    - 

******************************************************************************************

[Mon11 13:18] - ...lib/JumpScale/tools/actions/Action.py:666  - ERROR    - error in action: action: run                  runid:85.255.197.106:2200:cloudscalers (ERROR)
    test -d /etc && echo **OK** ; true | check_is_ok:True,showout:False

```

**Comment by islamTaha12** [comment]
I faced the same issue again.

**Comment by abdulrahmantkhalifa** [comment]
portforwarding on machine issue fixed ; ssh session was cached even after the session was existed big fixed on deployer bot machine ;
