### ISSUE TITLE
Macro errors in Cockpit Portal, again something with a expired JWT

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#95]
See below screenshot from the cockpit-demo: https://cockpit-demo.aydo2.com/home

![screen shot 2016-07-15 at 15 35 43](https://cloud.githubusercontent.com/assets/13795109/16875849/dd23dd52-4aa1-11e6-886e-add42846d425.png)

**Comment by abdulrahmantkhalifa** [comment]
cannot reproduce

**Comment by lzonneke** [comment]
duplicate
#102

**Comment by yveskerwyn** [comment]
@zaibon just updated the Moehaha Cockpit => again the JWT problem ////

**Comment by xmonader** [comment]
@yveskerwyn  Did you update the portal?

**Comment by yveskerwyn** [comment]
Yes and just did it again, same result:

**ERROR**: Could not execute macro vmgauge on home, error in macro. Error was:

Traceback (most recent call last):

File "/usr/local/lib/python3.5/dist-packages/JumpScale/portal/portal/MacroExecutor.py", line 312, in executeMacroOnContent

paramsExtra=paramsExtra, cmdstr=cmdstr, requestContext=ctx, content=content, page=page)

File "/opt/jumpscale8//lib/JumpScale/tools/taskletengine/TaskletEngine.py", line 115, in executeV2

return self.taskletEngines[groupname].executeV2(**args)

File "/opt/jumpscale8//lib/JumpScale/tools/taskletengine/TaskletEngine.py", line 254, in executeV2

params = tasklet.checkExecuteV2(args, params, tags)

File "/opt/jumpscale8//lib/JumpScale/tools/taskletengine/TaskletEngine.py", line 57, in checkExecuteV2

params = self.module.main(j, args, params, tags, self)

File "/optvar/cfg/portals/main/base/Cockpit/.macros/wiki/vmgauge/1_vmgauge.py", line 9, in main

[running.append(len(dockerhosts)) for dockerhosts in j.apps.system.atyourservice.listServices(role='dockerhost', ctx=args.requestContext).values()]

File "/optvar/cfg/portals/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py", line 101, in listServices

cl = self.get_client(**kwargs)

File "/optvar/cfg/portals/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py", line 32, in get_client

token = j.apps.system.oauthtoken.generateJwtToken(scope='', audience='', **kwargs)

File "/optvar/cfg/portals/portalbase/system/system__oauthtoken/methodclass/system_oauthtoken.py", line 50, in generateJwtToken

decoded = jwt.decode(resp.text, verify=False)

AttributeError: 'JWTToken' object has no attribute 'decode'

**Comment by zaibon** [comment]
It's not the same error. It's a bug in the new code. I just fix it in https://github.com/Jumpscale/jumpscale_portal8/commit/55592bcfeb9d1a9da59781c72f61f6045daed5d9

Please update portal again and let me know if there is still an issue

**Comment by yveskerwyn** [comment]
Yep solved, tx.
