### ISSUE TITLE
The cockpit trying to ssh to itself and this causes it to crash 

### ISSUE THREAD

**Issue by ashraffouda** [Jumpscale/jscockpit#97]
``` python 
*TRACEBACK*********************************************************************************

Traceback (most recent call last):
  File "/tmp/actions/85.255.197.108:2202:root/run.py", line 63, in run
    path = self.executor.execute("echo $PATH", showout=False)[1]
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 105, in execute
    retcode,out=self.sshclient.execute(cmds2,die=die,showout=showout, combinestdr=combinestdr)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 204, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 118, in transport
    if self.client is None:
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 141, in client
    raise j.exceptions.RuntimeError('Impossible to create SSH connection to %s:%s' % (self.addr, self.port))
OurExceptions.RuntimeError: ERROR: Impossible to create SSH connection to 85.255.197.108:2202 ((type:runtime.error)
[Sun17 09:45] - ...lib/JumpScale/tools/actions/Action.py:794  - ERROR    - 

```

**Comment by rkhamis** [comment]
I think this line is the culprit. We shouldn't be uploading the whole repo. Maybe the services without the recurring data? Needs investigation. https://github.com/Jumpscale/ays_jumpscale8/blob/master/_os/os.cockpit/actions.py#L231

**Comment by zaibon** [comment]
Relates to https://github.com/Jumpscale/ays_jumpscale8/issues/21
